name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to bump to without the v[...] prefix (e.g. 1.0.0-rc.5)"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - name: Enable corepack (yarn)
        run: corepack enable

      # This is not great, but as this does not happen in the actual release actions,
      # the worst that could happen is that this sneaks something in the PR diff.
      - name: Install Solana CLI
        run: |
          set -xeou pipefail
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"

      # This is not great, but as this does not happen in the actual release actions,
      # the worst that could happen is that this sneaks something in the PR diff.
      - name: Install Surfpool
        run: |
          curl -sL https://run.surfpool.run/ | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install cargo-release
        run: cargo install cargo-release --version 1.1.1 --locked

      - name: Bump version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          set -xeou pipefail

          # required for tests
          solana-keygen new --no-bip39-passphrase
          ./setup-tests.sh

          ./bump-version.sh "$VERSION"

      - name: Create release PR
        id: pull-request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          branch: release/v${{ inputs.version }}
          base: master
          commit-message: "v${{ inputs.version }}"
          title: "v${{ inputs.version }}"
          body: |
            Auto-generated release prep PR. **Please review the PR diff before merging.**

            Requested version: `${{ inputs.version }}`
            Triggered by: `${{ github.actor }}`
          delete-branch: true

      # GitHub does not trigger any workflows when automatically opening a PR to prevent recursion,
      # therefore we'll have to trigger all of the desired workflows manually :'(
      - name: Trigger tests for release PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          workflows=(
            release-pr.yaml
            #global-lint.yaml
            #tests.yaml
          )

          for workflow in "${workflows[@]}"; do
            gh workflow run "$workflow" --ref "${{ steps.pull-request.outputs.pull-request-branch }}"
          done
